In [89]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.externals import joblib
from sklearn.metrics import accuracy_score

In [90]:
from xgboost import XGBClassifier

In [94]:
dataset = pd.read_csv('')

In [95]:
dataset.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,207,208,209,210,211,212,213,214,215,0.1
0,0,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,...,-57.447461,-58.896493,-58.751002,-57.405669,-60.078475,-63.426811,-62.638537,-61.082741,-60.234652,male_calm
1,1,-65.707652,-65.707652,-63.114722,-61.518999,-61.097138,-63.424602,-63.720067,-56.854608,-55.168972,...,-39.792147,-40.613166,-41.209201,-41.439204,-43.994282,-49.399616,-50.591601,-49.144064,-48.705645,female_calm
2,2,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,...,-31.346553,-34.310774,-35.800705,-35.936112,-37.631846,-40.119408,-41.662903,-41.323644,-40.710780,male_calm
3,3,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,...,-48.674306,-48.596082,-47.602751,-43.049195,-42.659546,-43.188561,-44.001237,-43.610100,-44.698259,female_calm
4,4,-62.364311,-59.934725,-61.869600,-67.495764,-71.071811,-65.679826,-63.394396,-65.503349,-61.856639,...,-39.071328,-41.897121,-40.865430,-38.290605,-36.372397,-37.915779,-40.026125,-43.383777,-43.965398,male_calm

In [96]:
df = dataset.drop(dataset.columns[0],axis=1)

In [97]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,207,208,209,210,211,212,213,214,215,0.1
0,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,...,-57.447461,-58.896493,-58.751002,-57.405669,-60.078475,-63.426811,-62.638537,-61.082741,-60.234652,male_calm
1,-65.707652,-65.707652,-63.114722,-61.518999,-61.097138,-63.424602,-63.720067,-56.854608,-55.168972,-54.640002,...,-39.792147,-40.613166,-41.209201,-41.439204,-43.994282,-49.399616,-50.591601,-49.144064,-48.705645,female_calm
2,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,...,-31.346553,-34.310774,-35.800705,-35.936112,-37.631846,-40.119408,-41.662903,-41.323644,-40.710780,male_calm
3,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-65.928222,...,-48.674306,-48.596082,-47.602751,-43.049195,-42.659546,-43.188561,-44.001237,-43.610100,-44.698259,female_calm
4,-62.364311,-59.934725,-61.869600,-67.495764,-71.071811,-65.679826,-63.394396,-65.503349,-61.856639,-60.005421,...,-39.071328,-41.897121,-40.865430,-38.290605,-36.372397,-37.915779,-40.026125,-43.383777,-43.965398,male_calm

In [111]:
df= df.fillna(0)

In [112]:
factor = pd.factorize(df['0.1'])
df['0.1'] = factor[0]
definitions = factor[1]
definitions
df.head()

,0,1,2,3,4,5,6,7,8,9,...,207,208,209,210,211,212,213,214,215,0.1
0,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,-70.267764,...,-57.447461,-58.896493,-58.751002,-57.405669,-60.078475,-63.426811,-62.638537,-61.082741,-60.234652,0
1,-65.707652,-65.707652,-63.114722,-61.518999,-61.097138,-63.424602,-63.720067,-56.854608,-55.168972,-54.640002,...,-39.792147,-40.613166,-41.209201,-41.439204,-43.994282,-49.399616,-50.591601,-49.144064,-48.705645,1
2,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,-65.482499,...,-31.346553,-34.310774,-35.800705,-35.936112,-37.631846,-40.119408,-41.662903,-41.323644,-40.710780,0
3,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-64.528449,-65.928222,...,-48.674306,-48.596082,-47.602751,-43.049195,-42.659546,-43.188561,-44.001237,-43.610100,-44.698259,1
4,-62.364311,-59.934725,-61.869600,-67.495764,-71.071811,-65.679826,-63.394396,-65.503349,-61.856639,-60.005421,...,-39.071328,-41.897121,-40.865430,-38.290605,-36.372397,-37.915779,-40.026125,-43.383777,-43.965398,0

In [113]:
X = df.iloc[:,0:216].values
y = df.iloc[:,-1].values

In [114]:
X

array([[-70.26776416, -70.26776416, -70.26776416, ..., -62.63853671,
        -61.08274119, -60.23465213],
       [-65.7076524 , -65.7076524 , -63.11472242, ..., -50.59160101,
        -49.14406386, -48.70564479],
       [-65.48249888, -65.48249888, -65.48249888, ..., -41.66290318,
        -41.32364392, -40.71077984],
       ...,
       [-45.35121161, -46.38208057, -49.38114458, ..., -34.01047491,
        -21.49444497, -13.0382421 ],
       [-50.83803305, -49.72813607, -50.32184496, ..., -33.37555335,
        -24.63198588, -18.28419289],
       [-50.70232994, -50.60981999, -50.25894256, ..., -31.35073826,
        -18.68865851, -10.29118306]])

In [115]:
y

array([0, 1, 0, ..., 9, 8, 9], dtype=int64)

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 21)

In [117]:
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [118]:
y_pred = classifier.predict(X_test)

In [119]:
y_pred
y_test

array([9, 3, 4, 3, 7, 6, 5, 7, 6, 0, 4, 2, 9, 9, 9, 5, 6, 0, 2, 9, 3, 3,
       3, 1, 4, 6, 5, 9, 4, 0, 3, 0, 2, 8, 8, 0, 6, 6, 7, 4, 3, 0, 3, 1,
       8, 7, 5, 9, 8, 5, 0, 7, 5, 7, 5, 7, 6, 5, 2, 6, 3, 0, 0, 6, 2, 0,
       6, 0, 7, 8, 6, 6, 2, 5, 1, 6, 1, 1, 3, 3, 4, 0, 0, 9, 1, 5, 7, 8,
       4, 9, 4, 8, 9, 5, 5, 2, 7, 6, 3, 7, 7, 0, 0, 0, 8, 9, 9, 1, 3, 2,
       4, 0, 9, 4, 9, 4, 7, 6, 4, 6, 0, 0, 4, 3, 5, 5, 2, 8, 2, 9, 4, 0,
       9, 1, 6, 9, 6, 9, 4, 9, 0, 3, 7, 1, 3, 2, 3, 4, 4, 5, 9, 4, 9, 9,
       9, 2, 0, 9, 8, 1, 5, 9, 0, 0, 3, 8, 9, 1, 6, 1, 5, 0, 3, 7, 0, 2,
       4, 6, 8, 1, 7, 3, 4, 7, 4, 2, 4, 6, 7, 9, 6, 7, 8, 9, 0, 5, 0, 9,
       4, 7, 6, 9, 0, 0, 2, 9, 0, 3, 6, 8, 5, 5, 9, 6, 8, 7, 2, 8, 1, 0,
       6, 0, 4, 9, 5, 0, 4, 6, 5, 9, 6, 4, 0, 2, 7, 1, 3, 7, 3, 1, 6, 8,
       7, 5, 8, 0, 6, 8, 3, 3, 6, 8, 0, 2, 2, 1, 7, 1, 4, 5, 3, 4, 1, 6,
       7, 1, 0, 4, 2, 6, 6, 9, 2, 0, 3, 1, 8, 7, 8, 2, 5, 6, 0, 2, 7, 8,
       2, 3, 5, 7, 4, 2, 0, 3, 1, 4, 8, 4, 7, 4, 6, 9, 1, 8, 5, 0, 6, 1,
       3, 6, 6, 1, 4, 9, 3, 2, 8, 9, 8, 8, 1, 7, 1, 5, 5, 1, 2, 8, 5, 3,
       3, 0, 1, 8, 0, 9, 3, 4, 9, 4, 2, 9, 2, 2, 7, 0, 8, 7, 0, 1, 5, 7,
       9, 0, 7, 7, 2, 6, 5, 5, 6, 5, 9, 1, 3, 7, 5, 9, 3, 1, 0, 8, 2, 2,
       6, 4, 0, 3, 4, 1, 2, 3, 8, 9, 9, 6, 4, 4, 1, 5, 7, 6, 4, 6, 8, 1,
       8, 3, 3, 2, 7, 8, 1, 8, 3, 4, 1, 8, 2, 2, 7, 5, 8, 0, 6, 4, 4, 6,
       9, 6, 5, 4, 9, 7, 6, 0, 8, 2, 9, 1, 5, 8, 6, 4, 5, 1, 3, 5, 0, 8,
       3, 6, 8, 1, 9, 1, 8, 6, 6, 8, 1, 6, 0, 2, 6, 3, 6, 9, 8, 0, 8, 1,
       1, 9, 9, 1, 8, 6, 0, 7], dtype=int64)

In [120]:
accuracy_score(y_test,y_pred)

0.3851063829787234

In [121]:
reversefactor = dict(zip(range(10),definitions))
y_test = np.vectorize(reversefactor.get)(y_test)
y_pred = np.vectorize(reversefactor.get)(y_pred)

In [122]:
y_test

array(['female_fearful', 'female_happy', 'male_sad', 'female_happy',
       'female_angry', 'male_angry', 'female_sad', 'female_angry',
       'male_angry', 'male_calm', 'male_sad', 'male_happy',
       'female_fearful', 'female_fearful', 'female_fearful', 'female_sad',
       'male_angry', 'male_calm', 'male_happy', 'female_fearful',
       'female_happy', 'female_happy', 'female_happy', 'female_calm',
       'male_sad', 'male_angry', 'female_sad', 'female_fearful',
       'male_sad', 'male_calm', 'female_happy', 'male_calm', 'male_happy',
       'male_fearful', 'male_fearful', 'male_calm', 'male_angry',
       'male_angry', 'female_angry', 'male_sad', 'female_happy',
       'male_calm', 'female_happy', 'female_calm', 'male_fearful',
       'female_angry', 'female_sad', 'female_fearful', 'male_fearful',
       'female_sad', 'male_calm', 'female_angry', 'female_sad',
       'female_angry', 'female_sad', 'female_angry', 'male_angry',
       'female_sad', 'male_happy', 'male_angry', 'female_happy',
       'male_calm', 'male_calm', 'male_angry', 'male_happy', 'male_calm',
       'male_angry', 'male_calm', 'female_angry', 'male_fearful',
       'male_angry', 'male_angry', 'male_happy', 'female_sad',
       'female_calm', 'male_angry', 'female_calm', 'female_calm',
       'female_happy', 'female_happy', 'male_sad', 'male_calm',
       'male_calm', 'female_fearful', 'female_calm', 'female_sad',
       'female_angry', 'male_fearful', 'male_sad', 'female_fearful',
       'male_sad', 'male_fearful', 'female_fearful', 'female_sad',
       'female_sad', 'male_happy', 'female_angry', 'male_angry',
       'female_happy', 'female_angry', 'female_angry', 'male_calm',
       'male_calm', 'male_calm', 'male_fearful', 'female_fearful',
       'female_fearful', 'female_calm', 'female_happy', 'male_happy',
       'male_sad', 'male_calm', 'female_fearful', 'male_sad',
       'female_fearful', 'male_sad', 'female_angry', 'male_angry',
       'male_sad', 'male_angry', 'male_calm', 'male_calm', 'male_sad',
       'female_happy', 'female_sad', 'female_sad', 'male_happy',
       'male_fearful', 'male_happy', 'female_fearful', 'male_sad',
       'male_calm', 'female_fearful', 'female_calm', 'male_angry',
       'female_fearful', 'male_angry', 'female_fearful', 'male_sad',
       'female_fearful', 'male_calm', 'female_happy', 'female_angry',
       'female_calm', 'female_happy', 'male_happy', 'female_happy',
       'male_sad', 'male_sad', 'female_sad', 'female_fearful', 'male_sad',
       'female_fearful', 'female_fearful', 'female_fearful', 'male_happy',
       'male_calm', 'female_fearful', 'male_fearful', 'female_calm',
       'female_sad', 'female_fearful', 'male_calm', 'male_calm',
       'female_happy', 'male_fearful', 'female_fearful', 'female_calm',
       'male_angry', 'female_calm', 'female_sad', 'male_calm',
       'female_happy', 'female_angry', 'male_calm', 'male_happy',
       'male_sad', 'male_angry', 'male_fearful', 'female_calm',
       'female_angry', 'female_happy', 'male_sad', 'female_angry',
       'male_sad', 'male_happy', 'male_sad', 'male_angry', 'female_angry',
       'female_fearful', 'male_angry', 'female_angry', 'male_fearful',
       'female_fearful', 'male_calm', 'female_sad', 'male_calm',
       'female_fearful', 'male_sad', 'female_angry', 'male_angry',
       'female_fearful', 'male_calm', 'male_calm', 'male_happy',
       'female_fearful', 'male_calm', 'female_happy', 'male_angry',
       'male_fearful', 'female_sad', 'female_sad', 'female_fearful',
       'male_angry', 'male_fearful', 'female_angry', 'male_happy',
       'male_fearful', 'female_calm', 'male_calm', 'male_angry',
       'male_calm', 'male_sad', 'female_fearful', 'female_sad',
       'male_calm', 'male_sad', 'male_angry', 'female_sad',
       'female_fearful', 'male_angry', 'male_sad', 'male_calm',
       'male_happy', 'female_angry', 'female_calm', 'female_happy',
       'female_angry', 'female_happy', 'female_calm', 'male_angry',
       'male_fearful', 'female_angry', 'female_sad', 'male_fearful',
       'male_calm', 'male_angry', 'male_fearful', 'female_happy',
       'female_happy', 'male_angry', 'male_fearful', 'male_calm',
       'male_happy', 'male_happy', 'female_calm', 'female_angry',
       'female_calm', 'male_sad', 'female_sad', 'female_happy',
       'male_sad', 'female_calm', 'male_angry', 'female_angry',
       'female_calm', 'male_calm', 'male_sad', 'male_happy', 'male_angry',
       'male_angry', 'female_fearful', 'male_happy', 'male_calm',
       'female_happy', 'female_calm', 'male_fearful', 'female_angry',
       'male_fearful', 'male_happy', 'female_sad', 'male_angry',
       'male_calm', 'male_happy', 'female_angry', 'male_fearful',
       'male_happy', 'female_happy', 'female_sad', 'female_angry',
       'male_sad', 'male_happy', 'male_calm', 'female_happy',
       'female_calm', 'male_sad', 'male_fearful', 'male_sad',
       'female_angry', 'male_sad', 'male_angry', 'female_fearful',
       'female_calm', 'male_fearful', 'female_sad', 'male_calm',
       'male_angry', 'female_calm', 'female_happy', 'male_angry',
       'male_angry', 'female_calm', 'male_sad', 'female_fearful',
       'female_happy', 'male_happy', 'male_fearful', 'female_fearful',
       'male_fearful', 'male_fearful', 'female_calm', 'female_angry',
       'female_calm', 'female_sad', 'female_sad', 'female_calm',
       'male_happy', 'male_fearful', 'female_sad', 'female_happy',
       'female_happy', 'male_calm', 'female_calm', 'male_fearful',
       'male_calm', 'female_fearful', 'female_happy', 'male_sad',
       'female_fearful', 'male_sad', 'male_happy', 'female_fearful',
       'male_happy', 'male_happy', 'female_angry', 'male_calm',
       'male_fearful', 'female_angry', 'male_calm', 'female_calm',
       'female_sad', 'female_angry', 'female_fearful', 'male_calm',
       'female_angry', 'female_angry', 'male_happy', 'male_angry',
       'female_sad', 'female_sad', 'male_angry', 'female_sad',
       'female_fearful', 'female_calm', 'female_happy', 'female_angry',
       'female_sad', 'female_fearful', 'female_happy', 'female_calm',
       'male_calm', 'male_fearful', 'male_happy', 'male_happy',
       'male_angry', 'male_sad', 'male_calm', 'female_happy', 'male_sad',
       'female_calm', 'male_happy', 'female_happy', 'male_fearful',
       'female_fearful', 'female_fearful', 'male_angry', 'male_sad',
       'male_sad', 'female_calm', 'female_sad', 'female_angry',
       'male_angry', 'male_sad', 'male_angry', 'male_fearful',
       'female_calm', 'male_fearful', 'female_happy', 'female_happy',
       'male_happy', 'female_angry', 'male_fearful', 'female_calm',
       'male_fearful', 'female_happy', 'male_sad', 'female_calm',
       'male_fearful', 'male_happy', 'male_happy', 'female_angry',
       'female_sad', 'male_fearful', 'male_calm', 'male_angry',
       'male_sad', 'male_sad', 'male_angry', 'female_fearful',
       'male_angry', 'female_sad', 'male_sad', 'female_fearful',
       'female_angry', 'male_angry', 'male_calm', 'male_fearful',
       'male_happy', 'female_fearful', 'female_calm', 'female_sad',
       'male_fearful', 'male_angry', 'male_sad', 'female_sad',
       'female_calm', 'female_happy', 'female_sad', 'male_calm',
       'male_fearful', 'female_happy', 'male_angry', 'male_fearful',
       'female_calm', 'female_fearful', 'female_calm', 'male_fearful',
       'male_angry', 'male_angry', 'male_fearful', 'female_calm',
       'male_angry', 'male_calm', 'male_happy', 'male_angry',
       'female_happy', 'male_angry', 'female_fearful', 'male_fearful',
       'male_calm', 'male_fearful', 'female_calm', 'female_calm',
       'female_fearful', 'female_fearful', 'female_calm', 'male_fearful',
       'male_angry', 'male_calm', 'female_angry'], dtype='|S14')

In [123]:
cm = pd.crosstab(y_test, y_pred, rownames=['Actual emotions'], colnames=['Predicted emotions'])

In [124]:
cm

Predicted emotions,female_angry,female_calm,female_fearful,female_happy,female_sad,male_angry,male_calm,male_fearful,male_happy,male_sad
Actual emotions,,,,,,,,,,
female_angry,21,3,2,9,1,0,2,2,1,1
female_calm,2,27,3,3,6,0,1,0,1,2
female_fearful,7,6,9,18,9,0,2,2,0,0
female_happy,11,5,6,16,3,0,3,0,0,0
female_sad,2,13,2,9,15,0,0,0,0,0
male_angry,1,0,0,0,0,33,7,5,9,2
male_calm,0,1,1,0,1,1,23,1,13,14
male_fearful,1,2,0,5,0,10,7,10,11,2
male_happy,1,0,0,0,1,4,8,7,16,2
male_sad,1,0,1,1,0,1,20,5,6,11

In [134]:
import librosa

In [135]:
X, sample_rate = librosa.load('.wav', res_type='kaiser_fast',duration=2.5,sr=22050*2,offset=0.5)

In [136]:
sample_rate = np.array(sample_rate)
mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=13),axis=0)
featurelive = mfccs
livedf2 = featurelive

In [137]:
livedf2= pd.DataFrame(data=livedf2)
livedf2 = livedf2.stack().to_frame().T
livedf2

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,-14.077918,-15.226171,-16.640551,-15.690882,-14.981964,-13.345029,-12.011782,-12.369145,-14.733187,-12.065706,...,-34.983896,-37.688966,-37.954829,-35.772949,-34.632899,-34.563395,-34.604166,-33.104315,-32.4795,-33.086765

In [138]:
#twodim= np.expand_dims(livedf2, axis=2)

In [139]:
livedf2.columns = [col[0] for col in livedf2.columns]

In [140]:
X_test = livedf2.iloc[:,0:216].values

In [141]:
classifier = joblib.load('.pkl')

In [142]:
predict_test = classifier.predict(X_test)

In [143]:
predict_test

array([8], dtype=int64)

In [144]:
predict_test = np.vectorize(reversefactor.get)(predict_test)

In [145]:
predict_test

array(['male_fearful'], dtype='|S12')

In [1]:
joblib.dump(classifier, "")

NameError: name 'joblib' is not defined